/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.kikugie.wavebot

import com.kotlindiscord.kord.extensions.ExtensibleBot
import com.kotlindiscord.kord.extensions.utils.env
import dev.kord.common.entity.Snowflake
import dev.kord.core.Kord
import dev.kord.core.entity.Guild
import dev.kord.gateway.Intents
import dev.kord.gateway.PrivilegedIntent
import me.kikugie.wavebot.extensions.TicketExtension

val TEST_SERVER_ID = Snowflake(
    env("TEST_SERVER").toLong()  // Get the test server ID from the env vars or a .env file
)

private val TOKEN = env("TOKEN")   // Get the bot token from the env vars or a .env file

// Create a Kord instance
var guild: Guild? = null

@OptIn(PrivilegedIntent::class)
suspend fun main() {
    guild = Kord(env("TOKEN")).getGuildOrNull(TEST_SERVER_ID)

    val bot = ExtensibleBot(TOKEN) {
        intents { Intents.all }

        extensions {
            add(::TicketExtension)
        }
    }

    bot.start()
}
